[package]
name = "aphelios_search"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]

jieba-rs = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
zhconv = { workspace = true }
roxmltree = "0.21"
rbook = "0.7"

[features]
profiling = []
cpu = []
metal = []
cuda = []
