
[package]
name = "aphelios_voice"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]

aphelios_core = { path = "../aphelios_core" }
ort = { workspace = true }
indicatif = { workspace = true }
hound = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rustfft = { workspace = true }
tracing = { workspace = true }

[features]
default = ["metal"]
cuda = ["ort/cuda"]
metal = ["ort/coreml", "aphelios_core/metal"]
profiling = []
